### ISSUE TITLE
Profile button navigates to some other profile from Following list.

### ISSUE THREAD

**Issue by thisisartman** [CosmicPredator/AniMoe#10]
Instead of showing information about my profile, which is OkarinKyouma1820, it shows my friend's profile, CosmicPredator.
Here's a screen recording to help...

Additionally, the lists sometimes do not load... as seen in the recording.

https://github.com/CosmicPredator/AniMoe/assets/85949613/351fd156-8005-438a-b7f0-c987fe7e97c0

**Comment by CosmicPredator** [comment]
Hi, it is to be noted that the profile page is still under construction and that name is a placeholder name. I'm rereleasing V0.0.3 with Hotfix, but I didn't fixed the issue you mentioned in that release. Thanks
