### ISSUE TITLE
Navigation Pane has no titles

### ISSUE THREAD

**Issue by thisisartman** [CosmicPredator/AniMoe#3]
![image](https://github.com/CosmicPredator/AniMoe/assets/85949613/1e640a6d-5705-4424-b8ca-d5583ae32595)

**Comment by CosmicPredator** [comment]
I found the root cause of this issue, will fix in the next update...

**Comment by thisisartman** [comment]
> I found the root cause of this issue, will fix in the next update...

That's dope. Thanks!
