### ISSUE TITLE
Tachiyomi/Aniyomi feature parity?

### ISSUE THREAD

**Issue by thisisartman** [CosmicPredator/AniMoe#4]
[Tachiyomi](https://github.com/tachiyomiorg/tachiyomi) (an open source manga reading app) and [Aniyomi](https://github.com/aniyomiorg/aniyomi-preview/releases) (an anime focused fork of Tachiyomi) have the ability to connect websites via "extensions" that allow you to read manga or watch anime directly from the app. 

It also uses the Anilist integration to update directly to your profile your reading or watching progress...

Could we get this sort of functionality soon?

**Comment by CosmicPredator** [comment]
My app aims to be a pure anilist only client and nothing else. 

If u want a WinUi3 that can stream anime content, check out [this](https://github.com/insomniachi/Totoro).

**Comment by thisisartman** [comment]
> My app aims to be a pure anilist only client and nothing else. 
> 
> If u want a WinUi3 that can stream anime content, check out [this](https://github.com/insomniachi/Totoro).

Dude that is dope! Thanks alot!
